# Generated by Django 4.0 on 2022-01-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_class_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='classification',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
