# Generated by Django 4.0 on 2022-01-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_class_service', '0003_alter_image_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
